#!/bin/bash
# Use current working directory
#$ -wd /mnt/MD1200B/egarza/public/addimex_tms/derivatives/AMICO-v1.2.10/code/stdoutANDstderr_NodesUsed
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N AMICO-v1.2.10
#
# Number of subjects and maximum of concurrent tasks (-tc 5 -t 1-53)
#$ -t 1-50
#$ -q all.q@compute-00-14.cm.cluster
#
# Send an email only when there is an aborted task
#$ -m a
#$ -M victorissa.93@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load gcc/8.3.0
module load fsl/6.0.3
module load mrtrix3/3.0_RC3
module load ants/2.3.4
module load python37/3.7.6
module load freesurfer/6.0.0
#
# Write your commands in the next line
sub_list=($(ls -d /mnt/MD1200B/egarza/public/addimex_tms/derivatives/fmriprep/output_11FEB2020_fsr/freesurfer/sub-*/mri/orig.mgz | cut -d '/' -f 11))
export current_sub=${sub_list[$SGE_TASK_ID-1]}

echo Running job from $current_sub

cd ../..

export SUBJECTS_DIR=/mnt/MD1200B/egarza/public/addimex_tms/derivatives/AMICO-v1.2.10/sourcedata/fMRIPrep-v1.5.5/freesurfer

mri_vol2vol --mov "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-individual_desc-08NODDIfitdir_dwi.nii.gz" --targ code/IITmean_t1_256.nii.gz --o "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-MNI152Lin_desc-22NODDIfitdirinIITmean256_dwi.nii.gz" --lta "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-mni_desc-12fsorig2IITmean256_T1w.lta"

mri_vol2vol --mov "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-individual_desc-09NODDIfitICVF_dwi.nii.gz" --targ code/IITmean_t1_256.nii.gz --o "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-MNI152Lin_desc-23NODDIfitICVFinIITmean256_dwi.nii.gz" --lta "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-mni_desc-12fsorig2IITmean256_T1w.lta"

mri_vol2vol --mov "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-individual_desc-10NODDIfitISOVF_dwi.nii.gz" --targ code/IITmean_t1_256.nii.gz --o "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-MNI152Lin_desc-24NODDIfitISOVFinIITmean256_dwi.nii.gz" --lta "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-mni_desc-12fsorig2IITmean256_T1w.lta"

mri_vol2vol --mov "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-individual_desc-11NODDIfitOD_dwi.nii.gz" --targ code/IITmean_t1_256.nii.gz --o "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-MNI152Lin_desc-25NODDIfitODinIITmean256_dwi.nii.gz" --lta "${current_sub}/ses-t0/dwi/${current_sub}_ses-t0_space-mni_desc-12fsorig2IITmean256_T1w.lta"


